### ISSUE TITLE
Not Importing in Slic3r

### ISSUE THREAD

**Issue by Kavci034** [slic3r/slic3r-profiles#15]
Hello,

When I try to import the Creality configs(I didnt try other configs) slic3r doesnt import anything.
Only thing I get on %appdata%\Slic3r\printers:
```ini
# generated by Slic3r 1.3.0 on 

```

**Comment by supermerill** [comment]
this repo is for the merill-merge branch, not the current master one.

**Comment by Kavci034** [comment]
> this repo is for the merill-merge branch, not the current master one.

Will it ever work with the master branch

**Comment by supermerill** [comment]
When the merill-merge branch will be mature enough to be the new master.

**Comment by Kavci034** [comment]
@supermerill gave the answer
