### ISSUE TITLE
Voron Afterburner / Volcano presets have incorrect retraction

### ISSUE THREAD

**Issue by tanaes** [slic3r/slic3r-profiles#4]
Voron/Afterburner presets for Volcano nozzles all have standard retraction distances of 6.8 mm. This is likely an error carried over from a Bowden (Mobius) profile, and would be better corrected to 0.75 mm or thereabouts.

**Comment by supermerill** [comment]
I did that, that's the only change the "volcano" do to the setting.

**Comment by supermerill** [comment]
I rechecked and you're right.
i moved it to 2 mm, do you have a better value?

**Comment by tanaes** [comment]
Typical values run ≤1 mm for most of the DD Voron hotends. Mine (high-
flow Mosquito, equivalent melt path to Volcano) is at 0.6 mm.

On October 30, 2021, Github Notifications ***@***.***>
wrote:
> I rechecked and you're right.
>  i moved it to 2 mm, do you have a better value?
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/slic3r/slic3r-profiles/issues/4#issuecomment-
955588153>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AB7ISACLQOI3IFZKKDHYH4DUJRPNFANCNFSM457PUPDA>.

**Comment by supermerill** [comment]
The mosquito has a relly small hot zone compared to the volcano.
If possible, I'm okay to create profiles for moskito & dragon.
if you can send me your optimised profile, or better the specific of the mosquito!

**Comment by tanaes** [comment]
The total melt path length for the high-flow version is pretty similar
to a volcano. But maybe better, I can survey people on the discord and
get a consensus. 

On October 30, 2021, Github Notifications ***@***.***>
wrote:
> The mosquito has a relly small hot zone compared to the volcano.
>  If possible, I'm okay to create profiles for moskito & dragon.
>  if you can send me your optimised profile, or better the specific of
> the mosquito!
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/slic3r/slic3r-profiles/issues/4#issuecomment-
955599374>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AB7ISAGG7FMDXVZINTK4QQLUJR2QZANCNFSM457PUPDA>.

**Comment by supermerill** [comment]
Voron profiels may need a full review/rewrite now, anyway
