### ISSUE TITLE
Incorrect bridge_flow_ratio for Creality

### ISSUE THREAD

**Issue by fredrikbaberg** [slic3r/slic3r-profiles#7]
I first created this in supermerill/SuperSlicer/issues/1438 but noticed it should have been in this repository.

It seems the `bridge_flow_ratio` is specified in both decimal form and percentage in the files. In SuperSlicer I get a warning that the system preset has been modified from just being selected, which lead me to believe that the value should be in percentage.

I encountered this in https://github.com/slic3r/slic3r-profiles/blob/main/Creality.ini, have not checked if there are other cases.

I've linked a pull request, as it was a quick change, but have not tested it with printing.

**Comment by supermerill** [comment]
yeah.. i've done a path on those with the prusaslicer 2.3.2 merge.. I'm a bit late to push it, as i need to do some checks.

**Comment by supermerill** [comment]
Fixed since some months now.
